### ------------------------------------------------------------------------
### 1. REGISTRO Y LOGIN DE USUARIOS
### (Ejecuta estos pasos primero para obtener los Tokens)
### ------------------------------------------------------------------------

### 1.1 Registrar ALUMNO (Leandro)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "codigo": "20220001",
  "nombre": "Leandro Alumno",
  "password": "123",
  "rol": "alumno",
  "email": "leandro@ulima.edu.pe"
}

### 1.2 Login ALUMNO
# PASO IMPORTANTE: Copia el "token" de la respuesta para usarlo en Carrito y Pedidos.
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "codigo": "20220001",
  "password": "123"
}

### ------------------------------------------------------------------------

### 1.3 Registrar REPARTIDOR (Flash)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "codigo": "REP-001",
  "nombre": "Flash Repartidor",
  "password": "123",
  "rol": "repartidor",
  "email": "flash@ulexpress.pe"
}

### 1.4 Login REPARTIDOR
# PASO IMPORTANTE: Copia el "token" de la respuesta para usarlo en el archivo 06_Repartidor.
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "codigo": "REP-001",
  "password": "123"
}

### ------------------------------------------------------------------------

### 1.5 Registrar DUEÑO DE TIENDA (Para administrar productos)
# Nota: Necesitas que exista la Tienda ID 1 en la base de datos (Dunkin)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "codigo": "ADMIN-DUNKIN",
  "nombre": "Dunkin Admin",
  "password": "123",
  "rol": "tienda",
  "tiendaId": 1,
  "email": "dunkin@admin.com"
}

### 1.6 Login TIENDA
# Usa este token para añadir productos en el archivo 03_TiendasProductos.
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "codigo": "ADMIN-DUNKIN",
  "password": "123"
}