### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "codigo": "TEST-01",
  "password": "miPasswordVisible",
  "nombre": "Gerardo",
  "rol": "admin",
  "email": "test@test.com"
}

# LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "codigo": "TEST-01",
  "password": "miPasswordVisible"
}