### Obtener todas las tiendas
GET http://localhost:3000/api/tiendas

### Obtener tienda por ID
GET http://localhost:3000/api/tiendas/1
//GET http://localhost:3000/api/tiendas/2
//GET http://localhost:3000/api/tiendas/3


# REVISAR SI SE TIENE QUE CREAR ESTA LOGICA SEGUN LAS HU
### Crear tienda
POST http://localhost:3000/api/tiendas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiY29kaWdvIjoiMjAyMDEyMzQiLCJyb2wiOiJhbHVtbm8iLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTM4LCJleHAiOjE3NjM3OTM5Mzh9.PKrH9ieqiRQ-zlVTZGSGrk83ybtABwwvhnF_CGEX3DY

{
  "nombre": "Tienda Nueva",
  "ubicacion": "Av. Lima 123"
}

### Actualizar tienda
PUT http://localhost:3000/api/tiendas/1
Content-Type: application/json

{
  "nombre": "Tienda Actualizada"
}

### Eliminar tienda
DELETE http://localhost:3000/api/tiendas/1
