### 4.1 CREAR PEDIDO (Checkout Alumno)
# OJO: Usa IDs de productos reales que viste en 3.3
POST http://localhost:3000/api/pedidos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiY29kaWdvIjoiMjAyMDEyMzQiLCJyb2wiOiJhbHVtbm8iLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTM4LCJleHAiOjE3NjM3OTM5Mzh9.PKrH9ieqiRQ-zlVTZGSGrk83ybtABwwvhnF_CGEX3DY

{
  "metodoPago": "yape",
  "subtotal": 20.00,
  "delivery": 5.00,
  "total": 25.00,
  "items": [
    {
      "cantidad": 2,
      "producto": { "idProducto": 1, "nombre": "Café", "precio": 10.00 }
    }
  ]
}

# ^^^ COPIA EL ID QUE TE DEVUELVE ESTA PETICIÓN (ej: "00000001") ^^^

### 4.2 Ver Historial (Como Alumno)
GET http://localhost:3000/api/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiY29kaWdvIjoiMjAyMDEyMzQiLCJyb2wiOiJhbHVtbm8iLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTM4LCJleHAiOjE3NjM3OTM5Mzh9.PKrH9ieqiRQ-zlVTZGSGrk83ybtABwwvhnF_CGEX3DY

### 4.3 Ver Historial (Como Repartidor - Al principio vacío)
GET http://localhost:3000/api/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiY29kaWdvIjoiUkVQLTAwMSIsInJvbCI6InJlcGFydGlkb3IiLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTY4LCJleHAiOjE3NjM3OTM5Njh9.cAtkwocjYnJ8cymmjF2OAzzYCmF4xerA3z4g15X9g64

### 4.4 Ver Detalle de un Pedido
GET http://localhost:3000/api/pedidos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiY29kaWdvIjoiMjAyMDEyMzQiLCJyb2wiOiJhbHVtbm8iLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTM4LCJleHAiOjE3NjM3OTM5Mzh9.PKrH9ieqiRQ-zlVTZGSGrk83ybtABwwvhnF_CGEX3DY



### Actualizar estado del pedido
#router.put('/:id', verifyToken, pedidoController.updateOrder);
PUT http://localhost:3000/api/pedidos/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiY29kaWdvIjoiVEVTVC0wMSIsInJvbCI6ImFkbWluIiwidGllbmRhSWQiOm51bGwsImlhdCI6MTc2MzcwMjk3MSwiZXhwIjoxNzYzNzg5MzcxfQ.QuPBLgRqTcJX-RSUaFRJjeTNrA7rwIL6qO4uTGawLB0

{
  "estado": "ENTREGADO"
  //CREADO
  // CANCELADO
}

### Eliminar pedido
DELETE http://localhost:3000/api/pedidos/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiY29kaWdvIjoiVEVTVC0wMSIsInJvbCI6ImFkbWluIiwidGllbmRhSWQiOm51bGwsImlhdCI6MTc2MzcwMjk3MSwiZXhwIjoxNzYzNzg5MzcxfQ.QuPBLgRqTcJX-RSUaFRJjeTNrA7rwIL6qO4uTGawLB0
