### 5.1 Ver Pedidos Disponibles (Pantalla "Disponibles")
GET http://localhost:3000/api/repartidor/pedidos/disponibles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiY29kaWdvIjoiUkVQLTAwMSIsInJvbCI6InJlcGFydGlkb3IiLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTY4LCJleHAiOjE3NjM3OTM5Njh9.cAtkwocjYnJ8cymmjF2OAzzYCmF4xerA3z4g15X9g64

### 5.2 ACEPTAR PEDIDO (Pantalla "Disponibles" -> Botón Aceptar)
# Reemplaza el '1' por el ID del pedido creado en 4.1
PATCH http://localhost:3000/api/repartidor/pedidos/1/aceptar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiY29kaWdvIjoiUkVQLTAwMSIsInJvbCI6InJlcGFydGlkb3IiLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTY4LCJleHAiOjE3NjM3OTM5Njh9.cAtkwocjYnJ8cymmjF2OAzzYCmF4xerA3z4g15X9g64


### 5.3 Finalizar Pedido (Marcar entregado)
# Usamos la ruta genérica de actualizar estado
PUT http://localhost:3000/api/pedidos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiY29kaWdvIjoiUkVQLTAwMSIsInJvbCI6InJlcGFydGlkb3IiLCJ0aWVuZGFJZCI6bnVsbCwiaWF0IjoxNzYzNzA3NTY4LCJleHAiOjE3NjM3OTM5Njh9.cAtkwocjYnJ8cymmjF2OAzzYCmF4xerA3z4g15X9g64

{
  "estado": "ENTREGADO"
}